# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 06:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='цена')),
            ],
            options={
                'verbose_name': 'купон',
                'ordering': ['name'],
                'verbose_name_plural': 'купоны',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='название')),
                ('period', models.DurationField(verbose_name='период')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='цена')),
                ('discounts', models.IntegerField(default=0, verbose_name='процент скидки')),
                ('description', models.TextField(verbose_name='описание')),
                ('comments', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': 'скидка',
                'ordering': ['name'],
                'verbose_name_plural': 'скидыки',
            },
        ),
        migrations.CreateModel(
            name='Сontractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='название')),
            ],
            options={
                'verbose_name': 'контрагент',
                'ordering': ['name'],
                'verbose_name_plural': 'контрагенты',
            },
        ),
        migrations.AddField(
            model_name='stock',
            name='client',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.Сontractor', verbose_name='контрагент'),
        ),
        migrations.AddField(
            model_name='stock',
            name='coupon',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.Coupons', verbose_name='купон'),
        ),
    ]
