# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='цена')),
                ('description', models.TextField(verbose_name='описание')),
                ('photo', models.ImageField(blank=True, default='', upload_to='houses/photos', verbose_name='фотография')),
            ],
            options={
                'verbose_name': 'пица',
                'ordering': ['name'],
                'verbose_name_plural': 'пици',
            },
        ),
    ]
