# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=256, verbose_name='Фамилия')),
            ],
            options={
                'verbose_name_plural': 'клиенты',
                'verbose_name': 'клиент',
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Имя')),
            ],
            options={
                'verbose_name_plural': 'курьеры',
                'verbose_name': 'курьер',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=256, verbose_name='телефон')),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.Client', verbose_name='клиент')),
            ],
            options={
                'verbose_name_plural': 'клиенты',
                'verbose_name': 'клиент',
                'ordering': ['client'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='client_phone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='delivery.Phone', verbose_name='телефон'),
        ),
    ]
