# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20160815_2108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phone',
            options={'ordering': ['client'], 'verbose_name': 'телефон', 'verbose_name_plural': 'телефоны'},
        ),
    ]
