# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_auto_20160815_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=512, verbose_name='адрес')),
            ],
            options={
                'verbose_name_plural': 'алреса',
                'ordering': ['owner'],
                'verbose_name': 'адрес',
            },
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'ordering': ['owner'], 'verbose_name': 'телефон', 'verbose_name_plural': 'телефоны'},
        ),
        migrations.AlterModelOptions(
            name='pizza',
            options={'ordering': ['name'], 'verbose_name': 'пица', 'verbose_name_plural': 'пицы'},
        ),
        migrations.AlterField(
            model_name='client',
            name='client_phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='delivery.Phone', verbose_name='телефон'),
        ),
        migrations.AddField(
            model_name='address',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.Client', verbose_name='клиент'),
        ),
        migrations.AddField(
            model_name='client',
            name='client_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='delivery.Address', verbose_name='адрес'),
        ),
    ]
