# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_auto_20160815_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_order', models.IntegerField(default=0, verbose_name='количество заказов')),
                ('cash_back', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='возврат')),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.Client', verbose_name='клиент')),
            ],
            options={
                'verbose_name': 'бонус',
                'verbose_name_plural': 'бонусы',
                'ordering': ['owner'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.Address', verbose_name='адрес')),
                ('client', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.Client', verbose_name='клиент')),
                ('courier', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.Courier', verbose_name='курьер')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['date_time'],
            },
        ),
        migrations.CreateModel(
            name='OrderTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='количество')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='цена')),
                ('sum', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='сумма')),
                ('order_number', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.Order', verbose_name='заказ')),
                ('pizza', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.Pizza', verbose_name='пица')),
            ],
            options={
                'verbose_name': 'Таблична часть заказа',
                'verbose_name_plural': 'Табличные части заказа',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='order_table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='delivery.OrderTable', verbose_name='табличная часть'),
        ),
    ]
