# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 23:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_auto_20160815_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertable',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='pizza',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_table',
        ),
        migrations.DeleteModel(
            name='OrderTable',
        ),
    ]
