# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_auto_20160815_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='количество')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='цена')),
                ('sum', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='сумма')),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.Order', verbose_name='заказ')),
                ('pizza', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.Pizza', verbose_name='пица')),
            ],
            options={
                'verbose_name_plural': 'Табличные части заказа',
                'ordering': ['order'],
                'verbose_name': 'Таблична часть заказа',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='order_table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_table', to='delivery.OrderTable', verbose_name='табличная часть'),
        ),
    ]
